version: "3"

services:
  sharvebot:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: on-failure
    environment:
      - NAPCAT_GID=1000
      - NAPCAT_UID=1000
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099